"""add loans

Revision ID: 3160309ad025
Revises: 0dde5576f14c
Create Date: 2026-09-14 16:21:22.881458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3160309ad025'
down_revision: Union[str, Sequence[str], None] = '0dde5576f14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('borrowed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= borrowed_at', name='ck_loan_returned_after_borrowed'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_active_member', 'loans', ['member_id'], unique=False, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index('uq_loans_active_book', 'loans', ['book_id'], unique=True, postgresql_where=sa.text('returned_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_loans_active_book', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index('ix_loans_active_member', table_name='loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_table('loans')
    # ### end Alembic commands ###
