"""added server uuid defaults

Revision ID: 8b63bca1632d
Revises: 3160309ad025
Create Date: 2026-09-14 23:47:53.908445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b63bca1632d'
down_revision: Union[str, Sequence[str], None] = '3160309ad025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('books', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('loans', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('publishers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('staff', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
    
    # Manually added 
    authors_table = sa.table(
        "authors",
        sa.column("full_name", sa.String),
        sa.column("biography", sa.Text),
    )

    op.bulk_insert(
        authors_table,
        [
            {"full_name": "Fyodor Dostoyevsky", "biography": "Russian novelist and philosopher, author of Crime and Punishment and The Brothers Karamazov."},
            {"full_name": "James Joyce", "biography": "Irish novelist known for Ulysses and Finnegans Wake, a central figure in literary modernism."},
            {"full_name": "William Faulkner", "biography": "American novelist known for The Sound and the Fury and As I Lay Dying, Nobel laureate in Literature."},
            {"full_name": "Cormac McCarthy", "biography": "American novelist known for Blood Meridian and The Road, celebrated for his sparse, violent prose."},
            {"full_name": "Leo Tolstoy", "biography": "Russian author of War and Peace and Anna Karenina, regarded as one of the greatest novelists."},
            {"full_name": "Franz Kafka", "biography": "Bohemian novelist known for The Trial and The Metamorphosis, exploring alienation and absurdism."},
            {"full_name": "Virginia Woolf", "biography": "English modernist writer known for Mrs Dalloway and To the Lighthouse."},
            {"full_name": "Gabriel Garcia Marquez", "biography": "Colombian novelist and Nobel laureate, known for One Hundred Years of Solitude."},
            {"full_name": "Toni Morrison", "biography": "American novelist and Nobel laureate, known for Beloved and Song of Solomon."},
            {"full_name": "Vladimir Nabokov", "biography": "Russian-American novelist known for Lolita and Pale Fire."},
        ],
    )

    publishers_table = sa.table(
        "publishers",
        sa.column("name", sa.String),
        sa.column("website", sa.String),
        sa.column("contact_email", sa.String),
    )

    op.bulk_insert(
        publishers_table,
        [
            {"name": "Penguin Random House", "website": "https://www.penguinrandomhouse.com", "contact_email": "contact@penguinrandomhouse.com"},
            {"name": "HarperCollins", "website": "https://www.harpercollins.com", "contact_email": "contact@harpercollins.com"},
            {"name": "Simon & Schuster", "website": "https://www.simonandschuster.com", "contact_email": "contact@simonandschuster.com"},
            {"name": "Macmillan Publishers", "website": "https://us.macmillan.com", "contact_email": "contact@macmillan.com"},
            {"name": "Hachette Book Group", "website": "https://www.hachettebookgroup.com", "contact_email": "contact@hachettebookgroup.com"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""

    # Manually added
    # --- Reverse the seed data first ---
    op.execute("""
        DELETE FROM authors WHERE full_name IN (
            'Fyodor Dostoyevsky', 'James Joyce', 'William Faulkner', 'Cormac McCarthy',
            'Leo Tolstoy', 'Franz Kafka', 'Virginia Woolf', 'Gabriel Garcia Marquez',
            'Toni Morrison', 'Vladimir Nabokov'
        )
    """)
    op.execute("""
        DELETE FROM publishers WHERE name IN (
            'Penguin Random House', 'HarperCollins', 'Simon & Schuster',
            'Macmillan Publishers', 'Hachette Book Group'
        )
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('publishers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('loans', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('books', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('authors', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
